# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

os:
  - linux
  - osx
r:
  - oldrel
  - release
  - devel

r_check_args: --as-cran

branches:
  only:
  - master

r_github_packages:
  - jimhester/covr
r_binary_packages:
  - Rcpp
  - RcppArmadillo
  - roxygen2

after_success:
  - tar -C .. -xf $PKG_TARBALL
- Rscript -e 'covr::codecov()'